export const FETCH_TRANSACTIONS_LIST_REQUEST = 'FETCH_TRANSACTIONS_LIST_REQUEST';
export const FETCH_TRANSACTIONS_LIST_SUCCESS = 'FETCH_TRANSACTIONS_LIST_SUCCESS';
export const FETCH_TRANSACTIONS_LIST_FAILURE = 'FETCH_TRANSACTIONS_LIST_FAILURE';
export const TOGGLE_TRANSACTIONS_MODAL_POPUP = 'TOGGLE_TRANSACTIONS_MODAL_POPUP';
