export const FETCH_PORTFOLIO_REPORTS_REQUEST = 'FETCH_PORTFOLIO_REPORTS_REQUEST';
export const FETCH_PORTFOLIO_REPORTS_SUCCESS = 'FETCH_PORTFOLIO_REPORTS_SUCCESS';
export const FETCH_PORTFOLIO_REPORTS_FAILURE = 'FETCH_PORTFOLIO_REPORTS_FAILURE';

